### ISSUE TITLE
Banner

### ISSUE THREAD

**Issue by PSVXenithNetwork** [Xenith-Network/Suggestions#1]
I think that my banner ( http://imgur.com/a/zTo4I ) should be the new banner for Xenith Network on voting websites.

**Comment by JoeSmoe13** [comment]
I think that you  should be able to buy /warp end for a mil or something in skyblock when it comes out.
.

**Comment by Ronniie** [comment]
Gonna wait for more banners to come through. If we don't get any, this will be Xenith's Banner.
